# fly.toml app configuration file generated for utau-catalog on 2025-05-30T01:04:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'utau-catalog'
primary_region = 'syd'

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
  memory_mb = 1024
